application: vikgubbe
version: 1
runtime: python
api_version: 1



handlers:
- url: /javascripts
  static_dir: app/static/javascripts
  
- url: /stylesheets
  static_dir: app/static/stylesheets
  
- url: /images
  static_dir: app/static/images
  
- url: /favicon.ico
  static_files: app/static/favicon.ico
  upload: app/static/favicon.ico

- url: /admin/.*
  script: admin.py
  login: admin
  
- url: .*
  script: main.py

